server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: keynote-service
          uri: lb://KEYNOTE-SERVICE
          predicates:
            - Path=/keynote-service/**
          filters:
            - StripPrefix=1
        - id: conference-service
          uri: lb://CONFERENCE-SERVICE
          predicates:
            - Path=/conference-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://localhost:8080/realms/conference-realm
  jwk-set-uri: http://localhost:8080/realms/conference-realm/protocol/openid-connect/certs

